### ISSUE TITLE
memory_writer

### ISSUE THREAD

**Issue by alfr3one** [MarlBurroW/RLMarlbot#1]
```
from memory_writer import memory_writer
ImportError: DLL load failed while importing memory_writer: The specified module could not be found.
```

I think there is a problem with memory_writer.pyd. It is not being called correctly, even when running the exe.

**Comment by MarlBurroW** [comment]
Do you have this error on the release EXE or running the script with the installation commands ?

**Comment by alfr3one** [comment]
Both 
Im tty exe and python 
I got the same err on both ways

**Comment by MarlBurroW** [comment]
When you clone the repo, do you see memory_writer.pyd in the rlnexto_python/memory_writer directoy?

**Comment by alfr3one** [comment]
Yes memory_write.pyd + gitignore file in memory_writer folder 
And The path is read correctly

**Comment by MarlBurroW** [comment]
Do you use python x64 ?

**Comment by alfr3one** [comment]
Yes ofc x64

**Comment by alfr3one** [comment]
![image](https://github.com/MarlBurroW/RLMarlbot/assets/10384535/578fb571-f1e9-4d0f-bd4b-f32c9af9474c)
![image](https://github.com/MarlBurroW/RLMarlbot/assets/10384535/92115aae-7cfb-4904-8579-aeff3d4ea578)

both exe & command

**Comment by MarlBurroW** [comment]
Added you on discord

**Comment by Ensterrr** [comment]
hello Did you find a solution because I have the same problem

**Comment by attraktivist** [comment]
Traceback (most recent call last):
  File "C:\Windows\system32\RLMarlbot\rlnexto_python\main.py", line 3, in <module>
    from nexto.bot import Nexto
  File "C:\Windows\system32\RLMarlbot\rlnexto_python\nexto\bot.py", line 3, in <module>
    from rlbot.agents.base_agent import BaseAgent, SimpleControllerState
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-6Cl-Huy2-py3.12\Lib\site-packages\rlbot\agents\base_agent.py", line 4, in <module>
    from flatbuffers import Builder
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-6Cl-Huy2-py3.12\Lib\site-packages\flatbuffers\__init__.py", line 15, in <module>
    from .builder import Builder
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-6Cl-Huy2-py3.12\Lib\site-packages\flatbuffers\builder.py", line 15, in <module>
    from . import number_types as N
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-6Cl-Huy2-py3.12\Lib\site-packages\flatbuffers\number_types.py", line 18, in <module>
    from . import packer
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-6Cl-Huy2-py3.12\Lib\site-packages\flatbuffers\packer.py", line 22, in <module>
    from . import compat
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-6Cl-Huy2-py3.12\Lib\site-packages\flatbuffers\compat.py", line 19, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by typoEXE** [comment]
> Do you use python x64 ?

Which python version do you use?

**Comment by typoEXE** [comment]
> ```
> from memory_writer import memory_writer
> ImportError: DLL load failed while importing memory_writer: The specified module could not be found.
> ```
> 
> I think there is a problem with memory_writer.pyd. It is not being called correctly, even when running the exe.

Getting same issue as well.

**Comment by alfr3one** [comment]
@typoEXE uninstall python and instal python v 3.11.0 
its work for me

**Comment by typoEXE** [comment]
> @typoEXE uninstall python and install python v 3.11.0 its work for me

Fixed it, thanks! Looking forward to seeing improvements to this project. Will definitely keep it starred. If you guys have a discord, please send me over an invite! Discord: xtypo
