### ISSUE TITLE
Bot suddenly not working.

### ISSUE THREAD

**Issue by psxjtwr01** [MarlBurroW/RLMarlbot#33]
The bot perfectly worked yesterday and running it on an alt it got gc1 but today it suddenly stopped working I get this log
```
C:\Users\patri\OneDrive\Documents>marlbot-1.4.1.exe
pygame 2.5.2 (SDL 2.28.3, Python 3.11.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
RLMarlbot (Nexto) v1.4.0
You can change the settings in config.json
For keys binding, you can find values here: https://nerivec.github.io/old-ue4-wiki/pages/list-of-keygamepad-input-names.html
Please, give me a star on GitHub: https://github.com/MarlBurroW/RLMarlbot, this work takes a lot of time and effort
Select the bot to use:
1. Nexto
2. Necto
3. Seer (old version)
4. Element
Your choice (1/2/3/4): 1
Starting SDK...
Failed to start SDK:  Rocket League not found. Make sure Rocket League is running.
Traceback (most recent call last):
  File "rlsdk_python\sdk.py", line 62, in __init__
  File "pymem\__init__.py", line 55, in __init__
  File "pymem\__init__.py", line 275, in open_process_from_name
  File "pymem\__init__.py", line 297, in open_process_from_id
pymem.exception.CouldNotOpenProcess: Could not open process: 15920

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rlmarlbot\main.py", line 80, in start
  File "rlsdk_python\sdk.py", line 65, in __init__
Exception: Rocket League not found. Make sure Rocket League is running.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rlmarlbot\main.py", line 624, in <module>
  File "rlmarlbot\main.py", line 74, in __init__
  File "rlmarlbot\main.py", line 83, in start
NameError: name 'exit' is not defined
[24072] Failed to execute script 'main' due to unhandled exception!
```
Which only started happening after i installed rlsdk but i uninstalled it and got the same issue any ideas?

**Comment by psxjtwr01** [comment]
![image](https://github.com/MarlBurroW/RLMarlbot/assets/100047007/e139fc23-8787-47f6-9ecd-e2703594a8a8)

**Comment by MarlBurroW** [comment]
The script seems to not find the RocketLeague.exe process.
If you look into the task manager, do you see RocketLeague.exe ?

**Comment by AScriver** [comment]
Also make sure only one instance of Rocket League is running. I was running into this same error a few days ago when there was an unresponsive Rocket League instance running in the background.
