### ISSUE TITLE
Python ver.

### ISSUE THREAD

**Issue by zekurom** [MarlBurroW/RLMarlbot#4]
What version of python should I use to run the source code? Since some of the packages don't work with the most recent version.

**Comment by MarlBurroW** [comment]
I use python 3.11.0 x64

**Comment by zekurom** [comment]
I get an error saying that there's no module named "imp" which was supposedly deprecated in ver3.4

**Comment by zekurom** [comment]
`
python .\rlnexto_python\main.py

Traceback (most recent call last):
  File "C:\Users\aiden\OneDrive\Desktop\R.EX.A\EXP\Main\Steam-Epic-Uplay\Steam EXP\Rocket League\RLMarlbot\rlnexto_python\main.py", line 3, in <module>
    from nexto.bot import Nexto
  File "C:\Users\aiden\OneDrive\Desktop\R.EX.A\EXP\Main\Steam-Epic-Uplay\Steam EXP\Rocket League\RLMarlbot\rlnexto_python\nexto\bot.py", line 3, in <module>
    from rlbot.agents.base_agent import BaseAgent, SimpleControllerState
  File "C:\Users\aiden\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-xYoj3y79-py3.12\Lib\site-packages\rlbot\agents\base_agent.py", line 4, in <module>
    from flatbuffers import Builder
  File "C:\Users\aiden\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-xYoj3y79-py3.12\Lib\site-packages\flatbuffers\__init__.py", line 15, in <module>
    from .builder import Builder
  File "C:\Users\aiden\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-xYoj3y79-py3.12\Lib\site-packages\flatbuffers\builder.py", line 15, in <module>
    from . import number_types as N
  File "C:\Users\aiden\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-xYoj3y79-py3.12\Lib\site-packages\flatbuffers\number_types.py", line 18, in <module>
    from . import packer
  File "C:\Users\aiden\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-xYoj3y79-py3.12\Lib\site-packages\flatbuffers\packer.py", line 22, in <module>
    from . import compat
  File "C:\Users\aiden\AppData\Local\pypoetry\Cache\virtualenvs\rlnexto-python-xYoj3y79-py3.12\Lib\site-packages\flatbuffers\compat.py", line 19, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
`
